# Use Miniforge with CUDA support
FROM rapidsai/miniforge-cuda:latest

# Set environment variables for CUDA (optional, but helps with compatibility)
ENV CUDA_HOME=/usr/local/cuda
ENV PATH="${CUDA_HOME}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}"

# run commands in a bash login shell
SHELL ["/bin/bash", "-l", "-c"]

# Create non-root user/group with default inputs
ARG UID=1000
ARG GID=1000

RUN groupadd -g "${GID}" --system dist_user && \
    useradd -l -u "${UID}" -g "${GID}" --system -d /home/rapids -m  -s /bin/bash dist_user && \
    chown -R dist_user:dist_user /opt

# Switch to non-root user
USER dist_user
WORKDIR /home/rapids

# Ensures we cached mamba install per
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache
COPY --chown=dist_user:dist_user environment_gpu.yml /home/rapids/dist-s1/environment_gpu.yml
COPY --chown=dist_user:dist_user . /home/rapids/dist-s1

# Ensure all files are read/write by the user
# RUN chmod -R 777 /home/rapids

# Create the environment with mamba
RUN mamba env create -f /home/rapids/dist-s1/environment_gpu.yml && \
    conda clean -afy

# Ensure that environment is activated on startup and interactive shell
RUN echo "conda activate dist-s1-env" >> ~/.bashrc

# Install repository with pip
RUN python -m pip install --no-cache-dir /home/rapids/dist-s1
